In [1]:
###06)Quem teve mais transacao de streak
import pandas as pd

In [4]:
transacoes = pd.read_csv("../data/transacoes.csv", sep=";")
clientes = pd.read_csv("../data/clientes.csv", sep=";")
produtos_transacoes = pd.read_csv("../data/transacao_produto.csv", sep=";")
produtos = pd.read_csv("../data/produtos.csv", sep = ";")

In [6]:
produtos_transacoes.head(5)

,idTransacaoProduto,IdTransacao,IdProduto,QtdeProduto,vlProduto
0,000026d0-4d4e-4fed-934a-9e5b26d9e379,d59d9859-8fb9-41cc-a296-be38c4dce8e4,5,1,1
1,00002f54-dd03-4b3f-ade0-22c3e61df8c2,519241fd-2676-49b2-8e74-0acc09a08f69,5,1,1
2,00004ee3-b894-4b8c-a36b-9480f0e643f3,03173ea0-9f4c-47fe-9982-5743027d1253,11,1,50
3,00006a7d-c83a-44ca-aad9-e8a2a2f1b64d,73993c42-d18f-4f51-82c4-25e13c29962c,11,1,50
4,0000991a-e6ae-4b9f-8747-c6cfe77890dd,db341350-16e4-49ea-96d4-c3e991e7c8c0,5,1,1

In [7]:
transacoes.head(5)

,IdTransacao,IdCliente,DtCriacao,QtdePontos,DescSistemaOrigem
0,0000520a-a4e5-4977-b360-17be62fa0f2b,24782f0b-4683-4f35-976a-ea21d6714ba6,2025-09-17 12:28:41.864,1,twitch
1,000060e8-aa76-4286-a8d7-f30e6fa47edd,252a0923-3f79-45bb-b664-3040235c6c58,2024-07-23 12:49:49.874,1,twitch
2,000095de-3daa-4cfb-a0ae-e7b2c8bc3c9b,30f45a6d-ada5-4a17-8338-710e414eb6c6,2025-09-17 13:38:57.479,1,twitch
3,0000c010-a592-46f7-8b0b-6f841bee64ba,65662aff-44d6-4f06-b9d9-07445c6e5943,2025-10-03 12:23:39.779,1,twitch
4,0000dfbb-e14e-4ea7-a57f-60236869fffe,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,2024-02-20 13:21:45.613,1,twitch

In [29]:
produtos.head(30)

,IdProduto,DescNomeProduto,DescDescricaoProduto,DescCategoriaProduto
0,001 - Espada Longa,Espada Longa,Uma espada longa de aço.,espada
1,002 - Espada Curta,Espada Curta,Espada leve e rápida.,espada
2,003 - Armadura de Couro,Armadura de Couro,Armadura leve feita de couro.,armadura
3,004 - Armadura de Placas,Armadura de Placas,Armadura pesada de placas metálicas.,armadura
4,005 - Botas de Agilidade,Botas de Agilidade,Botas que aumentam a destreza.,botas
5,006 - Botas de Força,Botas de Força,Botas reforçadas para guerreiros.,botas
6,007 - Cajado de Fogo,Cajado de Fogo,Cajado mágico que lança fogo.,cajado
7,008 - Cajado de Gelo,Cajado de Gelo,Cajado mágico que lança gelo.,cajado
8,009 - Chapéu do Mago,Chapéu do Mago,Chapéu pontudo que aumenta inteligência.,chapeu
9,010 - Chapéu do Sábio,Chapéu do Sábio,Chapéu que aumenta sabedoria.,chapeu
10,011 - Espada Bastarda,Espada Bastarda,Espada de duas mãos.,espada
11,012 - Armadura de Escamas,Armadura de Escamas,Armadura feita de escamas de dragão.,armadura
12,013 - Botas Silenciosas,Botas Silenciosas,Botas que aumentam furtividade.,botas
13,014 - Cajado da Vida,Cajado da Vida,Cajado que aumenta sabedoria.,cajado
14,015 - Chapéu do Ladino,Chapéu do Ladino,Chapéu que aumenta destreza.,chapeu
15,016 - Espada Curvada,Espada Curvada,Espada exótica e afiada.,espada
16,017 - Armadura Mística,Armadura Mística,Armadura leve que aumenta inteligência.,armadura
17,018 - Botas do Vento,Botas do Vento,Botas que aumentam velocidade.,botas
18,019 - Cajado do Trovão,Cajado do Trovão,Cajado que invoca raios.,cajado
19,020 - Chapéu do Guerreiro,Chapéu do Guerreiro,Chapéu que aumenta força.,chapeu
20,021 - Espada Flamejante,Espada Flamejante,Espada que emite chamas.,espada
21,022 - Armadura de Sombras,Armadura de Sombras,Armadura que aumenta furtividade.,armadura
22,023 - Botas de Velocidade,Botas de Velocidade,Botas que aumentam a velocidade de movimento.,botas
23,024 - Cajado da Terra,Cajado da Terra,Cajado que invoca tremores.,cajado
24,025 - Espada do Caos,Espada do Caos,Espada que causa dano imprevisível.,espada
25,026 - Armadura de Luz,Armadura de Luz,Armadura que aumenta sabedoria.,armadura
26,027 - Botas de Ferro,Botas de Ferro,Botas pesadas que aumentam força.,botas
27,028 - Cajado do Vento,Cajado do Vento,Cajado que invoca rajadas de vento.,cajado
28,029 - Espada de Gelo,Espada de Gelo,Espada que congela inimigos.,espada
29,030 - Armadura de Fogo,Armadura de Fogo,Armadura que protege contra chamas.,armadura

In [23]:
##lembrando que chave nao recebe sufixos, por isso nao tem nenhum sufixo

cliente_joined = transacoes.merge(
    produtos_transacoes,
    on=["IdTransacao"],
    how="left",
    suffixes=["_x", "_y"]
)

In [24]:
cliente_joined.head(2)

,IdTransacao,IdCliente,DtCriacao,QtdePontos,DescSistemaOrigem,idTransacaoProduto,IdProduto,QtdeProduto,vlProduto
0,0000520a-a4e5-4977-b360-17be62fa0f2b,24782f0b-4683-4f35-976a-ea21d6714ba6,2025-09-17 12:28:41.864,1,twitch,dbbfdc7c-84b2-4536-b1a8-abb7a475875c,5,1,1
1,000060e8-aa76-4286-a8d7-f30e6fa47edd,252a0923-3f79-45bb-b664-3040235c6c58,2024-07-23 12:49:49.874,1,twitch,9d90f1a5-2442-429f-a913-37f2734979ef,5,1,1

In [25]:
cliente_joined[["IdTransacao", "IdCliente", "IdProduto"]]

,IdTransacao,IdCliente,IdProduto
0,0000520a-a4e5-4977-b360-17be62fa0f2b,24782f0b-4683-4f35-976a-ea21d6714ba6,5
1,000060e8-aa76-4286-a8d7-f30e6fa47edd,252a0923-3f79-45bb-b664-3040235c6c58,5
2,000095de-3daa-4cfb-a0ae-e7b2c8bc3c9b,30f45a6d-ada5-4a17-8338-710e414eb6c6,5
3,0000c010-a592-46f7-8b0b-6f841bee64ba,65662aff-44d6-4f06-b9d9-07445c6e5943,5
4,0000dfbb-e14e-4ea7-a57f-60236869fffe,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,5
...,...,...,...
323213,ffff52de-13fb-4405-a797-fddb5b4a48c5,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,5
323214,ffffb5ab-047e-43e4-bab3-ee2d19e9b7db,961622c3-3c29-4fa1-88d2-4f408d6d6ebb,5
323215,ffffc72e-d882-47f0-b933-cfd92c7e6621,2d3d2dce-d353-4961-ad39-46723efe2100,5
323216,ffffcd29-600c-4ae0-89b2-c62457eafc3f,c1a8d13d-cca9-4372-b195-9b0770d81a0d,5
323217,fffff928-9a18-4741-a516-3a92351d1d72,65662aff-44d6-4f06-b9d9-07445c6e5943,5

In [26]:
df_full = cliente_joined.merge(
    produtos,
    right_on=["IdProduto"],
    left_on=["IdProduto"],
    how = "left"
)

In [27]:
df_full.head(15)

,IdTransacao,IdCliente,DtCriacao,QtdePontos,DescSistemaOrigem,idTransacaoProduto,IdProduto,QtdeProduto,vlProduto,DescNomeProduto,DescDescricaoProduto,DescCategoriaProduto
0,0000520a-a4e5-4977-b360-17be62fa0f2b,24782f0b-4683-4f35-976a-ea21d6714ba6,2025-09-17 12:28:41.864,1,twitch,dbbfdc7c-84b2-4536-b1a8-abb7a475875c,5,1,1,ChatMessage,NaN,chat
1,000060e8-aa76-4286-a8d7-f30e6fa47edd,252a0923-3f79-45bb-b664-3040235c6c58,2024-07-23 12:49:49.874,1,twitch,9d90f1a5-2442-429f-a913-37f2734979ef,5,1,1,ChatMessage,NaN,chat
2,000095de-3daa-4cfb-a0ae-e7b2c8bc3c9b,30f45a6d-ada5-4a17-8338-710e414eb6c6,2025-09-17 13:38:57.479,1,twitch,ff90b953-f715-4b97-b511-c4f78f725f33,5,1,1,ChatMessage,NaN,chat
3,0000c010-a592-46f7-8b0b-6f841bee64ba,65662aff-44d6-4f06-b9d9-07445c6e5943,2025-10-03 12:23:39.779,1,twitch,a31fc987-77e0-4510-b9c8-769f4d0714a4,5,1,1,ChatMessage,NaN,chat
4,0000dfbb-e14e-4ea7-a57f-60236869fffe,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,2024-02-20 13:21:45.613,1,twitch,85293b0c-399d-4590-a2a8-9943825d62e9,5,1,1,ChatMessage,NaN,chat
5,0000e94f-fb76-42b7-82e3-5059b6e40703,3884c92f-a635-4b67-9e5a-97730829cdca,2024-02-05 13:27:18.987,1,twitch,1a05616b-e315-4209-8639-0271570b97a1,5,1,1,ChatMessage,NaN,chat
6,00017768-81eb-45ae-ad56-f189dd657808,3b878853-34a5-44be-9a8e-05642b853dc6,2025-09-30 12:02:16.448,1,twitch,17bc0ff0-183e-46b6-82a7-b4892387a04b,5,1,1,ChatMessage,NaN,chat
7,00019b46-6b25-47c3-aa8f-f550d7dbcb00,e2624c1c-c8af-4622-94e0-f3470037292f,2024-06-20 19:22:45.600,1,twitch,aa76f012-cd7e-4eb0-b47a-2edc5bd945a5,5,1,1,ChatMessage,NaN,chat
8,0001caa0-39a5-4620-baaa-5f6d8db3a412,7df60476-b880-485a-9430-ededf50a9bbb,2026-02-25 12:52:50.780,1,twitch,2a2d1f41-1dfe-49bd-9d03-c3d71da14b8c,5,1,1,ChatMessage,NaN,chat
9,0001d503-58d0-4c3e-b0f4-eda1d5f97d06,9aba2685-7c0a-4d1f-8e22-0c47ca0af580,2024-03-18 13:04:21.814,1,twitch,a49ea736-1013-42d8-95cb-dc4be6896ddb,5,1,1,ChatMessage,NaN,chat
10,0001fa55-581a-44e6-8e40-1bb44f82de8e,05de679b-9989-4416-9aa4-20c149999c8d,2024-07-11 13:46:05.759,1,twitch,a666b652-2af5-444d-8599-e2e1080370ce,5,1,1,ChatMessage,NaN,chat
11,000219b4-75c8-4c76-8752-56eaf744bbe0,4fade907-6e0f-4581-a674-aad6622b1b10,2024-08-30 13:43:05.591,1,twitch,5d7eaef7-58db-4547-8f88-a732d5d3269c,5,1,1,ChatMessage,NaN,chat
12,00028d36-4575-4d02-b2a0-bdae1bc83231,9d023e72-c799-40c0-907a-96e023a97959,2024-11-11 12:36:33.625,50,twitch,1ef265c6-16f4-470d-83f6-80c6f5d1d62b,11,1,50,Lista de presença,NaN,present
13,00028f94-1cf3-413c-91dd-652dc1a9e161,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,2024-02-05 11:54:38.711,1,twitch,421b9b3c-0e3a-4779-bff3-3d92e622f9de,5,1,1,ChatMessage,NaN,chat
14,00029103-193c-4c63-9cc6-f6f3fbbfbd51,f19aaa00-f337-4174-ba14-a2a39dd6ebbf,2025-09-18 12:02:03.817,1,twitch,b51776f1-7494-4e82-8057-a3be9a280f84,5,1,1,ChatMessage,NaN,chat

In [ ]:
df_full_filtrado = df_full[df_full["descProduto"] == "Presença Streak"]

In [ ]:
(df_full_filtrado.groupby(by=["IdCliente"])["IdTransacao"].count().sort_values(ascending=False).head(1))