In [1]:
##### da pra usar apply pra usar função linha a linha no pandas, pra nao precisar usar for.
#pra lista tuplas ou outros iteraveis -> map.
# colunas de dataframe ->>> apply

In [2]:
import pandas as pd
import requests
from io import StringIO

In [3]:
url = "https://pt.wikipedia.org/wiki/Unidades_federativas_do_Brasil"
headers = {
    "User-Agent": "Mozilla/5.0"
}

In [4]:
response = requests.get(url, headers=headers)
response.raise_for_status()

In [5]:

response = requests.get(url, headers=headers)
response.raise_for_status()

dfs = pd.read_html(StringIO(response.text))

dfs[1].head()

,Bandeira,Unidade federativa,Abreviação,Sede de governo,Área (km²),População (Censo 2022),Densidade (2005),PIB (2015),(% total) (2015),PIB per capita (R$) (2015),IDH (2010),Alfabetização (2016),Mortalidade infantil (2016),Expectativa de vida (2016)
0,NaN,Acre,AC,Rio Branco,"164 122,2",830 018,430,13 622 000,2,"16 953,46",663,"86,9%","17,0‰","73,9 anos"
1,NaN,Alagoas,AL,Maceió,"27 767,7",3 127 683,10861,46 364 000,8,"13 877,53",631,"80,6%","19,5‰","71,6 anos"
2,NaN,Amapá,AP,Macapá,"142 814,6",733 759,416,13 861 000,2,"18 079,54",708,95%,"23,2‰","73,9 anos"
3,NaN,Amazonas,AM,Manaus,"1 570 745,7",3 941 613,205,86 560 000,14,"21 978,95",674,"93,1%","18,2‰","71,9 anos"
4,NaN,Bahia,BA,Salvador,"564 692,7",14 141 626,2446,245 025 000,41,"16 115,89",660,87%,"17,3‰","73,5 anos"

In [6]:
df_uf = dfs[1]

In [7]:
df_uf.columns

Index(['Bandeira', 'Unidade federativa', 'Abreviação', 'Sede de governo',
       'Área (km²)', 'População (Censo 2022)', 'Densidade (2005)',
       'PIB (2015)', '(% total) (2015)', 'PIB per capita (R$) (2015)',
       'IDH (2010)', 'Alfabetização (2016)', 'Mortalidade infantil (2016)',
       'Expectativa de vida (2016)'],
      dtype='str')

In [8]:
def str_to_float(x: str):
    x = float(x.replace(" ", "").replace(",",".").replace("\xa0", ""))
    return float(x)

In [9]:
df_uf["Área (km²)"].head(5)

0      164 122,2
1       27 767,7
2      142 814,6
3    1 570 745,7
4      564 692,7
Name: Área (km²), dtype: str

In [10]:
df_uf["Área (km²)"] = df_uf["Área (km²)"].apply(str_to_float)

In [11]:
df_uf.head(5)

,Bandeira,Unidade federativa,Abreviação,Sede de governo,Área (km²),População (Censo 2022),Densidade (2005),PIB (2015),(% total) (2015),PIB per capita (R$) (2015),IDH (2010),Alfabetização (2016),Mortalidade infantil (2016),Expectativa de vida (2016)
0,NaN,Acre,AC,Rio Branco,164122.2,830 018,430,13 622 000,2,"16 953,46",663,"86,9%","17,0‰","73,9 anos"
1,NaN,Alagoas,AL,Maceió,27767.7,3 127 683,10861,46 364 000,8,"13 877,53",631,"80,6%","19,5‰","71,6 anos"
2,NaN,Amapá,AP,Macapá,142814.6,733 759,416,13 861 000,2,"18 079,54",708,95%,"23,2‰","73,9 anos"
3,NaN,Amazonas,AM,Manaus,1570745.7,3 941 613,205,86 560 000,14,"21 978,95",674,"93,1%","18,2‰","71,9 anos"
4,NaN,Bahia,BA,Salvador,564692.7,14 141 626,2446,245 025 000,41,"16 115,89",660,87%,"17,3‰","73,5 anos"

In [12]:
df_uf["População (Censo 2022)"] = df_uf["População (Censo 2022)"].apply(str_to_float)

In [13]:
df_uf.head(5)

,Bandeira,Unidade federativa,Abreviação,Sede de governo,Área (km²),População (Censo 2022),Densidade (2005),PIB (2015),(% total) (2015),PIB per capita (R$) (2015),IDH (2010),Alfabetização (2016),Mortalidade infantil (2016),Expectativa de vida (2016)
0,NaN,Acre,AC,Rio Branco,164122.2,830018.0,430,13 622 000,2,"16 953,46",663,"86,9%","17,0‰","73,9 anos"
1,NaN,Alagoas,AL,Maceió,27767.7,3127683.0,10861,46 364 000,8,"13 877,53",631,"80,6%","19,5‰","71,6 anos"
2,NaN,Amapá,AP,Macapá,142814.6,733759.0,416,13 861 000,2,"18 079,54",708,95%,"23,2‰","73,9 anos"
3,NaN,Amazonas,AM,Manaus,1570745.7,3941613.0,205,86 560 000,14,"21 978,95",674,"93,1%","18,2‰","71,9 anos"
4,NaN,Bahia,BA,Salvador,564692.7,14141626.0,2446,245 025 000,41,"16 115,89",660,87%,"17,3‰","73,5 anos"

In [14]:
df_uf["PIB (2015)"] = df_uf["PIB (2015)"].apply(str_to_float)
df_uf["PIB per capita (R$) (2015)"] = df_uf["PIB per capita (R$) (2015)"].apply(str_to_float)

In [15]:
df_uf.dtypes

Bandeira                       float64
Unidade federativa                 str
Abreviação                         str
Sede de governo                    str
Área (km²)                     float64
População (Censo 2022)         float64
Densidade (2005)                 int64
PIB (2015)                     float64
(% total) (2015)                 int64
PIB per capita (R$) (2015)     float64
IDH (2010)                       int64
Alfabetização (2016)               str
Mortalidade infantil (2016)        str
Expectativa de vida (2016)         str
dtype: object

In [16]:
df_uf.head(5)

,Bandeira,Unidade federativa,Abreviação,Sede de governo,Área (km²),População (Censo 2022),Densidade (2005),PIB (2015),(% total) (2015),PIB per capita (R$) (2015),IDH (2010),Alfabetização (2016),Mortalidade infantil (2016),Expectativa de vida (2016)
0,NaN,Acre,AC,Rio Branco,164122.2,830018.0,430,13622000.0,2,16953.46,663,"86,9%","17,0‰","73,9 anos"
1,NaN,Alagoas,AL,Maceió,27767.7,3127683.0,10861,46364000.0,8,13877.53,631,"80,6%","19,5‰","71,6 anos"
2,NaN,Amapá,AP,Macapá,142814.6,733759.0,416,13861000.0,2,18079.54,708,95%,"23,2‰","73,9 anos"
3,NaN,Amazonas,AM,Manaus,1570745.7,3941613.0,205,86560000.0,14,21978.95,674,"93,1%","18,2‰","71,9 anos"
4,NaN,Bahia,BA,Salvador,564692.7,14141626.0,2446,245025000.0,41,16115.89,660,87%,"17,3‰","73,5 anos"

In [17]:
def exp_to_anos(exp):
    return float(exp.replace(",",".").replace(" anos", ""))

In [18]:
import pandas as pd

df = pd.DataFrame({
    'vendas': [100, 200, 300]
})

df['vendas_dobradas'] = df['vendas'].apply(lambda x: x * 2)

In [19]:
df_uf["Expectativa de vida (2016)"] = df_uf["Expectativa de vida (2016)"].apply(exp_to_anos)

In [20]:
df_uf.head(5)

,Bandeira,Unidade federativa,Abreviação,Sede de governo,Área (km²),População (Censo 2022),Densidade (2005),PIB (2015),(% total) (2015),PIB per capita (R$) (2015),IDH (2010),Alfabetização (2016),Mortalidade infantil (2016),Expectativa de vida (2016)
0,NaN,Acre,AC,Rio Branco,164122.2,830018.0,430,13622000.0,2,16953.46,663,"86,9%","17,0‰",73.9
1,NaN,Alagoas,AL,Maceió,27767.7,3127683.0,10861,46364000.0,8,13877.53,631,"80,6%","19,5‰",71.6
2,NaN,Amapá,AP,Macapá,142814.6,733759.0,416,13861000.0,2,18079.54,708,95%,"23,2‰",73.9
3,NaN,Amazonas,AM,Manaus,1570745.7,3941613.0,205,86560000.0,14,21978.95,674,"93,1%","18,2‰",71.9
4,NaN,Bahia,BA,Salvador,564692.7,14141626.0,2446,245025000.0,41,16115.89,660,87%,"17,3‰",73.5

In [21]:
import pandas as pd

df = pd.DataFrame({
    'vendas': [100, 200, 300]
})

df['vendas_dobradas'] = df['vendas'].apply(lambda x: x * 2)

In [22]:
df

   vendas  vendas_dobradas
0     100              200
1     200              400
2     300              600

In [23]:
def uf_to_region(uf):
    uf = uf.strip().casefold()

    if uf in ["acre", "amapá", "amazonas", "pará", "rondônia", "roraima", "tocantins"]:
        return "Norte"
    elif uf in ["alagoas", "bahia", "ceará", "maranhão", "paraíba", "pernambuco", "piauí", "rio grande do norte", "sergipe"]:
         return "Nordeste"
    elif uf in ["distrito federal", "goiás", "mato grosso", "mato grosso do sul"]:
        return "Centro-Oeste"
    elif uf in ["espírito santo", "minas gerais", "rio de janeiro", "são paulo"]:
        return "Sudeste"
    elif uf in ["paraná", "rio grande do sul", "santa catarina"]:
         return "Sul"
    else:
        return "UF inválida"

In [24]:
#### tipo um case when

df_uf["Regiao"] = df_uf["Unidade federativa"].apply(uf_to_region)

In [25]:
df_uf.head(5)

,Bandeira,Unidade federativa,Abreviação,Sede de governo,Área (km²),População (Censo 2022),Densidade (2005),PIB (2015),(% total) (2015),PIB per capita (R$) (2015),IDH (2010),Alfabetização (2016),Mortalidade infantil (2016),Expectativa de vida (2016),Regiao
0,NaN,Acre,AC,Rio Branco,164122.2,830018.0,430,13622000.0,2,16953.46,663,"86,9%","17,0‰",73.9,Norte
1,NaN,Alagoas,AL,Maceió,27767.7,3127683.0,10861,46364000.0,8,13877.53,631,"80,6%","19,5‰",71.6,Nordeste
2,NaN,Amapá,AP,Macapá,142814.6,733759.0,416,13861000.0,2,18079.54,708,95%,"23,2‰",73.9,Norte
3,NaN,Amazonas,AM,Manaus,1570745.7,3941613.0,205,86560000.0,14,21978.95,674,"93,1%","18,2‰",71.9,Norte
4,NaN,Bahia,BA,Salvador,564692.7,14141626.0,2446,245025000.0,41,16115.89,660,87%,"17,3‰",73.5,Nordeste

In [26]:
df_uf.columns

Index(['Bandeira', 'Unidade federativa', 'Abreviação', 'Sede de governo',
       'Área (km²)', 'População (Censo 2022)', 'Densidade (2005)',
       'PIB (2015)', '(% total) (2015)', 'PIB per capita (R$) (2015)',
       'IDH (2010)', 'Alfabetização (2016)', 'Mortalidade infantil (2016)',
       'Expectativa de vida (2016)', 'Regiao'],
      dtype='str')

In [ ]:
#se pib/capita > 30.000 e mortalidade ser menor que 15/1000 e IDH > 700 "Parece bom" e tudo que nao for, Nao parece bom

In [27]:
def mortalidade_to_float(x):
    x = x.replace("‰", "").replace(",", ".")
    return x
df_uf["Mortalidade infantil (2016)(/1000)"] = df_uf["Mortalidade infantil (2016)"].apply(mortalidade_to_float)

In [28]:
df_uf.head(5)

,Bandeira,Unidade federativa,Abreviação,Sede de governo,Área (km²),População (Censo 2022),Densidade (2005),PIB (2015),(% total) (2015),PIB per capita (R$) (2015),IDH (2010),Alfabetização (2016),Mortalidade infantil (2016),Expectativa de vida (2016),Regiao,Mortalidade infantil (2016)(/1000)
0,NaN,Acre,AC,Rio Branco,164122.2,830018.0,430,13622000.0,2,16953.46,663,"86,9%","17,0‰",73.9,Norte,17.0
1,NaN,Alagoas,AL,Maceió,27767.7,3127683.0,10861,46364000.0,8,13877.53,631,"80,6%","19,5‰",71.6,Nordeste,19.5
2,NaN,Amapá,AP,Macapá,142814.6,733759.0,416,13861000.0,2,18079.54,708,95%,"23,2‰",73.9,Norte,23.2
3,NaN,Amazonas,AM,Manaus,1570745.7,3941613.0,205,86560000.0,14,21978.95,674,"93,1%","18,2‰",71.9,Norte,18.2
4,NaN,Bahia,BA,Salvador,564692.7,14141626.0,2446,245025000.0,41,16115.89,660,87%,"17,3‰",73.5,Nordeste,17.3

In [33]:
#quando faz axis = o ele passa coluna coluna, qnd passa axis = 1 ele vai linha a linha tipo:
#padroa é axis =0 que é colun a coluna

df_uf.apply(lambda x: x["PIB per capita (R$) (2015)"], axis=1)

0     16953.46
1     13877.53
2     18079.54
3     21978.95
4     16115.89
5     14669.14
6     73971.05
7     30627.45
8     26265.32
9     11366.23
10    32894.96
11    31337.22
12    24884.94
13    16009.98
14    14133.32
15    33768.62
16    16795.34
17    12218.51
18    39826.95
19    16631.86
20    33960.36
21    20677.95
22    20476.71
23    36525.28
24    43694.68
25    17189.28
26    19094.16
dtype: float64

In [29]:
#serie -> da linha
df_uf.iloc[0]

Bandeira                                     NaN
Unidade federativa                          Acre
Abreviação                                    AC
Sede de governo                       Rio Branco
Área (km²)                              164122.2
População (Censo 2022)                  830018.0
Densidade (2005)                             430
PIB (2015)                            13622000.0
(% total) (2015)                               2
PIB per capita (R$) (2015)              16953.46
IDH (2010)                                   663
Alfabetização (2016)                       86,9%
Mortalidade infantil (2016)                17,0‰
Expectativa de vida (2016)                  73.9
Regiao                                     Norte
Mortalidade infantil (2016)(/1000)          17.0
Name: 0, dtype: object

In [ ]:
linha["PIB per capita (R$) (2015)"] > 30000 and linha["Mortalidade infantil (2016)(/1000)"] < 15 and linha["IDH (2010)"] > 700

In [42]:
def classifi_bom(linha: pd.Series) -> str:
    if (
        linha["PIB per capita (R$) (2015)"] > 30000
        and linha["Mortalidade infantil (2016)(/1000)"] < 15
        and linha["IDH (2010)"] > 700
    ):
        return "Parece bom"
    else:
        return "Parece estar abaixo"


# def classifi_bom(linha: pd.Series) -> str:
#     return "Parece bom" if (
#         linha["PIB per capita (R$) (2015)"] > 30000
#         and linha["Mortalidade infantil (2016)(/1000)"] < 15
#         and linha["IDH (2010)"] > 700
#     ) else "Parece estar abaixo"

In [38]:
df_uf["Mortalidade infantil (2016)(/1000)"] = df_uf["Mortalidade infantil (2016)(/1000)"].astype(float)

In [44]:
### axis -> o padrão é coluna 0 // recebe linha a linha dps aplica nas linhas (vindo no formato de séries)

df_uf["classificacao"] = df_uf.apply(classifi_bom, axis=1)

In [45]:
df_uf.head(5)

,Bandeira,Unidade federativa,Abreviação,Sede de governo,Área (km²),População (Censo 2022),Densidade (2005),PIB (2015),(% total) (2015),PIB per capita (R$) (2015),IDH (2010),Alfabetização (2016),Mortalidade infantil (2016),Expectativa de vida (2016),Regiao,Mortalidade infantil (2016)(/1000),classificacao
0,NaN,Acre,AC,Rio Branco,164122.2,830018.0,430,13622000.0,2,16953.46,663,"86,9%","17,0‰",73.9,Norte,17.0,Parece estar abaixo
1,NaN,Alagoas,AL,Maceió,27767.7,3127683.0,10861,46364000.0,8,13877.53,631,"80,6%","19,5‰",71.6,Nordeste,19.5,Parece estar abaixo
2,NaN,Amapá,AP,Macapá,142814.6,733759.0,416,13861000.0,2,18079.54,708,95%,"23,2‰",73.9,Norte,23.2,Parece estar abaixo
3,NaN,Amazonas,AM,Manaus,1570745.7,3941613.0,205,86560000.0,14,21978.95,674,"93,1%","18,2‰",71.9,Norte,18.2,Parece estar abaixo
4,NaN,Bahia,BA,Salvador,564692.7,14141626.0,2446,245025000.0,41,16115.89,660,87%,"17,3‰",73.5,Nordeste,17.3,Parece estar abaixo