In [1]:
import pandas as pd

In [2]:
df_clientes = pd.read_csv("../data/clientes.csv", sep=";")

In [3]:
df_clientes.head(5)

,idCliente,flEmail,flTwitch,flYouTube,flBlueSky,flInstagram,qtdePontos,DtCriacao,DtAtualizacao
0,000dc0f6-e4f2-4a42-b8cd-b586ed1c709a,0,1,0,0,0,2,2025-11-13 12:03:56.114,2025-12-13 11:45:37.364
1,000ff655-fa9f-4baa-a108-47f581ec52a1,0,0,0,0,0,25086,2024-02-01 00:00:00.000,2025-09-26 13:28:37.697
2,001749bd-37b5-4b1e-8111-f9fbba90f530,0,0,0,0,0,50,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000
3,0019bb9e-26d4-4ebf-8727-fc911ea28a92,0,0,0,0,0,2,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000
4,0028dda2-334f-40bb-9582-475fb6719471,1,1,1,0,0,1100,2025-10-29 02:08:18.367,2026-02-24 04:49:02.551

In [13]:
df_clientes.head(5)

,idCliente,flEmail,flTwitch,flYouTube,flBlueSky,flInstagram,qtdePontos,DtCriacao,DtAtualizacao
0,000dc0f6-e4f2-4a42-b8cd-b586ed1c709a,0,1,0,0,0,2,2025-11-13 12:03:56.114,2025-12-13 11:45:37.364
1,000ff655-fa9f-4baa-a108-47f581ec52a1,0,0,0,0,0,25086,2024-02-01 00:00:00.000,2025-09-26 13:28:37.697
2,001749bd-37b5-4b1e-8111-f9fbba90f530,0,0,0,0,0,50,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000
3,0019bb9e-26d4-4ebf-8727-fc911ea28a92,0,0,0,0,0,2,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000
4,0028dda2-334f-40bb-9582-475fb6719471,1,1,1,0,0,1100,2025-10-29 02:08:18.367,2026-02-24 04:49:02.551

In [24]:
def get_last_id(x):
    return x.split("-")[-1]

In [25]:
df_clientes["idCliente"].apply(get_last_id)

0       b586ed1c709a
1       47f581ec52a1
2       f9fbba90f530
3       fc911ea28a92
4       475fb6719471
            ...
5467    fdaaa0da172a
5468    04a4155f5634
5469    e01a6fd830f0
5470    509b48ed31b4
5471    3bbda4e50f7a
Name: idCliente, Length: 5472, dtype: str