In [9]:
import pandas as pd
import requests
from io import StringIO

headers = {"User-Agent": "Mozilla/5.0 (compatible; meu-script/1.0)"}

url = "https://pt.wikipedia.org/wiki/Unidades_federativas_do_Brasil"

response = requests.get(url, headers=headers)
dfs = pd.read_html(StringIO(response.text))

# %%
uf = dfs[1]

In [10]:

uf.dtypes

Bandeira                       float64
Unidade federativa                 str
Abreviação                         str
Sede de governo                    str
Área (km²)                         str
População (Censo 2022)             str
Densidade (2005)                 int64
PIB (2015)                         str
(% total) (2015)                 int64
PIB per capita (R$) (2015)         str
IDH (2010)                       int64
Alfabetização (2016)               str
Mortalidade infantil (2016)        str
Expectativa de vida (2016)         str
dtype: object

In [11]:
def str_to_float(x):
    x = float(x.replace(" ", "")
              .replace(",",".")
              .replace("\xa0", ""))
    return x

In [12]:
uf["Área (km²)"] = uf["Área (km²)"].apply(str_to_float)
uf["População (Censo 2022)"] = uf["População (Censo 2022)"].apply(str_to_float)

In [13]:
uf.dtypes

Bandeira                       float64
Unidade federativa                 str
Abreviação                         str
Sede de governo                    str
Área (km²)                     float64
População (Censo 2022)         float64
Densidade (2005)                 int64
PIB (2015)                         str
(% total) (2015)                 int64
PIB per capita (R$) (2015)         str
IDH (2010)                       int64
Alfabetização (2016)               str
Mortalidade infantil (2016)        str
Expectativa de vida (2016)         str
dtype: object

In [14]:
uf["PIB per capita (R$) (2015)"] = uf["PIB per capita (R$) (2015)"].apply(str_to_float)

In [16]:
def exp_to_anos(exp):
    return float(exp.replace(",", ".").replace(" anos",""))

uf["Expectativa de vida (2016)"] = uf["Expectativa de vida (2016)"].apply(exp_to_anos)

In [17]:
uf

,Bandeira,Unidade federativa,Abreviação,Sede de governo,Área (km²),População (Censo 2022),Densidade (2005),PIB (2015),(% total) (2015),PIB per capita (R$) (2015),IDH (2010),Alfabetização (2016),Mortalidade infantil (2016),Expectativa de vida (2016)
0,NaN,Acre,AC,Rio Branco,164122.2,830018.0,430,13 622 000,2,16953.46,663,"86,9%","17,0‰",73.9
1,NaN,Alagoas,AL,Maceió,27767.7,3127683.0,10861,46 364 000,8,13877.53,631,"80,6%","19,5‰",71.6
2,NaN,Amapá,AP,Macapá,142814.6,733759.0,416,13 861 000,2,18079.54,708,95%,"23,2‰",73.9
3,NaN,Amazonas,AM,Manaus,1570745.7,3941613.0,205,86 560 000,14,21978.95,674,"93,1%","18,2‰",71.9
4,NaN,Bahia,BA,Salvador,564692.7,14141626.0,2446,245 025 000,41,16115.89,660,87%,"17,3‰",73.5
5,NaN,Ceará,CE,Fortaleza,148825.6,8794957.0,5440,130 621 000,22,14669.14,682,"84,8%","14,4‰",73.8
6,NaN,Distrito Federal,DF,Brasília,5822.1,2817381.0,40073,215 613 000,36,73971.05,824,"97,4%","10,5‰",78.1
7,NaN,Espírito Santo,ES,Vitória,46077.5,3833712.0,7397,120 363 000,2,30627.45,740,"93,8%","8,8‰",78.2
8,NaN,Goiás,GO,Goiânia,340086.7,7056495.0,1652,173 632 000,29,26265.32,735,"93,5%","14,9‰",74.2
9,NaN,Maranhão,MA,São Luís,331983.3,6755805.0,1838,78 475 000,13,11366.23,639,"83,3%","21,3‰",70.6
10,NaN,Mato Grosso,MT,Cuiabá,903357.9,3658649.0,310,107 418 000,18,32894.96,725,"93,5%","16,9‰",74.2
11,NaN,Mato Grosso do Sul,MS,Campo Grande,357125.0,2757013.0,634,83 082 000,14,31337.22,729,"93,7%","14,0‰",75.5
12,NaN,Minas Gerais,MG,Belo Horizonte,586528.3,20539989.0,3279,519 326 000,87,24884.94,731,"93,8%","10,9‰",77.2
13,NaN,Pará,PA,Belém,1247689.5,8121025.0,558,130 883 000,22,16009.98,646,"90,7%","16,6‰",72.1
14,NaN,Paraíba,PB,João Pessoa,56439.8,3974687.0,6371,56 140 000,9,14133.32,658,"83,7%","16,1‰",73.2
15,NaN,Paraná,PR,Curitiba,199314.9,11444380.0,5148,376 960 000,63,33768.62,749,"95,5%","9,3‰",77.1
16,NaN,Pernambuco,PE,Recife,98311.6,9058931.0,8558,156 955 000,26,16795.34,673,"87,2%","12,7‰",73.9
17,NaN,Piauí,PI,Teresina,251529.2,3271199.0,1195,39 148 000,7,12218.51,646,"82,8%","19,1‰",71.1
18,NaN,Rio de Janeiro,RJ,Rio de Janeiro,43696.1,16055174.0,35205,659 137 000,11,39826.95,761,"97,3%","11,5‰",76.2
19,NaN,Rio Grande do Norte,RN,Natal,52796.8,3302729.0,5688,57 250 000,1,16631.86,684,"85,3%","14,7‰",75.7
20,NaN,Rio Grande do Sul,RS,Porto Alegre,281748.5,11882965.0,3849,381 985 000,64,33960.36,746,"96,8%","9,6‰",77.8
21,NaN,Rondônia,RO,Porto Velho,237576.2,1581196.0,646,36 563 000,6,20677.95,690,"93,3%","20,0‰",71.3
22,NaN,Roraima,RR,Boa Vista,224299.0,636707.0,174,10 354 000,2,20476.71,707,"93,4%","17,2‰",71.5
23,NaN,Santa Catarina,SC,Florianópolis,95346.2,7610361.0,6153,249 073 000,42,36525.28,774,"97,2%","9,2‰",79.1
24,NaN,São Paulo,SP,São Paulo,248209.4,44411238.0,16293,1 939 890 000,324,43694.68,783,"97,2%","9,9‰",78.1
25,NaN,Sergipe,SE,Aracaju,21910.3,2210004.0,8981,38 554 000,6,17189.28,665,"85,3%","16,2‰",72.7
26,NaN,Tocantins,TO,Palmas,277620.9,1511460.0,470,28 930 000,5,19094.16,699,"89,6%","15,8‰",73.4

In [18]:
def uf_to_regiao(uf):
    if uf in ["Distrito Federal", "Goiás", "Mato Grosso", "Mato Grosso do Sul"]:
        return "Centro-Oeste"
    elif uf in ["Alagoas", "Bahia", "Ceará", "Maranhão", "Paraíba", "Pernambuco", "Piauí", "Rio Grande do Norte", "Sergipe"]:
        return "Nordeste"
    elif uf in ["Acre", "Amapá", "Amazonas", "Pará", "Rondônia", "Roraima", "Tocantins"]:
        return "Norte"
    elif uf in ["Espírito Santo", "Minas Gerais", "Rio de Janeiro", "São Paulo"]:
        return "Sudeste"
    elif uf in ["Paraná", "Rio Grande do Sul", "Santa Catarina"]:
        return "Sul"

In [20]:
uf["Regiao"] = uf["Unidade federativa"].apply(uf_to_regiao)

In [21]:
uf

,Bandeira,Unidade federativa,Abreviação,Sede de governo,Área (km²),População (Censo 2022),Densidade (2005),PIB (2015),(% total) (2015),PIB per capita (R$) (2015),IDH (2010),Alfabetização (2016),Mortalidade infantil (2016),Expectativa de vida (2016),Regiao
0,NaN,Acre,AC,Rio Branco,164122.2,830018.0,430,13 622 000,2,16953.46,663,"86,9%","17,0‰",73.9,Norte
1,NaN,Alagoas,AL,Maceió,27767.7,3127683.0,10861,46 364 000,8,13877.53,631,"80,6%","19,5‰",71.6,Nordeste
2,NaN,Amapá,AP,Macapá,142814.6,733759.0,416,13 861 000,2,18079.54,708,95%,"23,2‰",73.9,Norte
3,NaN,Amazonas,AM,Manaus,1570745.7,3941613.0,205,86 560 000,14,21978.95,674,"93,1%","18,2‰",71.9,Norte
4,NaN,Bahia,BA,Salvador,564692.7,14141626.0,2446,245 025 000,41,16115.89,660,87%,"17,3‰",73.5,Nordeste
5,NaN,Ceará,CE,Fortaleza,148825.6,8794957.0,5440,130 621 000,22,14669.14,682,"84,8%","14,4‰",73.8,Nordeste
6,NaN,Distrito Federal,DF,Brasília,5822.1,2817381.0,40073,215 613 000,36,73971.05,824,"97,4%","10,5‰",78.1,Centro-Oeste
7,NaN,Espírito Santo,ES,Vitória,46077.5,3833712.0,7397,120 363 000,2,30627.45,740,"93,8%","8,8‰",78.2,Sudeste
8,NaN,Goiás,GO,Goiânia,340086.7,7056495.0,1652,173 632 000,29,26265.32,735,"93,5%","14,9‰",74.2,Centro-Oeste
9,NaN,Maranhão,MA,São Luís,331983.3,6755805.0,1838,78 475 000,13,11366.23,639,"83,3%","21,3‰",70.6,Nordeste
10,NaN,Mato Grosso,MT,Cuiabá,903357.9,3658649.0,310,107 418 000,18,32894.96,725,"93,5%","16,9‰",74.2,Centro-Oeste
11,NaN,Mato Grosso do Sul,MS,Campo Grande,357125.0,2757013.0,634,83 082 000,14,31337.22,729,"93,7%","14,0‰",75.5,Centro-Oeste
12,NaN,Minas Gerais,MG,Belo Horizonte,586528.3,20539989.0,3279,519 326 000,87,24884.94,731,"93,8%","10,9‰",77.2,Sudeste
13,NaN,Pará,PA,Belém,1247689.5,8121025.0,558,130 883 000,22,16009.98,646,"90,7%","16,6‰",72.1,Norte
14,NaN,Paraíba,PB,João Pessoa,56439.8,3974687.0,6371,56 140 000,9,14133.32,658,"83,7%","16,1‰",73.2,Nordeste
15,NaN,Paraná,PR,Curitiba,199314.9,11444380.0,5148,376 960 000,63,33768.62,749,"95,5%","9,3‰",77.1,Sul
16,NaN,Pernambuco,PE,Recife,98311.6,9058931.0,8558,156 955 000,26,16795.34,673,"87,2%","12,7‰",73.9,Nordeste
17,NaN,Piauí,PI,Teresina,251529.2,3271199.0,1195,39 148 000,7,12218.51,646,"82,8%","19,1‰",71.1,Nordeste
18,NaN,Rio de Janeiro,RJ,Rio de Janeiro,43696.1,16055174.0,35205,659 137 000,11,39826.95,761,"97,3%","11,5‰",76.2,Sudeste
19,NaN,Rio Grande do Norte,RN,Natal,52796.8,3302729.0,5688,57 250 000,1,16631.86,684,"85,3%","14,7‰",75.7,Nordeste
20,NaN,Rio Grande do Sul,RS,Porto Alegre,281748.5,11882965.0,3849,381 985 000,64,33960.36,746,"96,8%","9,6‰",77.8,Sul
21,NaN,Rondônia,RO,Porto Velho,237576.2,1581196.0,646,36 563 000,6,20677.95,690,"93,3%","20,0‰",71.3,Norte
22,NaN,Roraima,RR,Boa Vista,224299.0,636707.0,174,10 354 000,2,20476.71,707,"93,4%","17,2‰",71.5,Norte
23,NaN,Santa Catarina,SC,Florianópolis,95346.2,7610361.0,6153,249 073 000,42,36525.28,774,"97,2%","9,2‰",79.1,Sul
24,NaN,São Paulo,SP,São Paulo,248209.4,44411238.0,16293,1 939 890 000,324,43694.68,783,"97,2%","9,9‰",78.1,Sudeste
25,NaN,Sergipe,SE,Aracaju,21910.3,2210004.0,8981,38 554 000,6,17189.28,665,"85,3%","16,2‰",72.7,Nordeste
26,NaN,Tocantins,TO,Palmas,277620.9,1511460.0,470,28 930 000,5,19094.16,699,"89,6%","15,8‰",73.4,Norte

In [22]:
uf.dtypes

Bandeira                       float64
Unidade federativa                 str
Abreviação                         str
Sede de governo                    str
Área (km²)                     float64
População (Censo 2022)         float64
Densidade (2005)                 int64
PIB (2015)                         str
(% total) (2015)                 int64
PIB per capita (R$) (2015)     float64
IDH (2010)                       int64
Alfabetização (2016)               str
Mortalidade infantil (2016)        str
Expectativa de vida (2016)     float64
Regiao                             str
dtype: object