In [ ]:
### Sumarização dos dados

In [1]:
import pandas as pd

In [9]:
clientes = pd.read_csv("../data/clientes.csv", sep=";")

In [4]:
idades = [12,14,20,22,44,46,33,32,45,12,10,11,14,26,46,36,32,31,30]
idades = pd.Series(idades)
idades

0     12
1     14
2     20
3     22
4     44
5     46
6     33
7     32
8     45
9     12
10    10
11    11
12    14
13    26
14    46
15    36
16    32
17    31
18    30
dtype: int64

In [ ]:
### estatisitca -> Nada mais é representar os dados a partir de um único valor.
# Agregação -> agregando os dados, tiveer expremendo os dados e representa com 1 (Seja soma, minimo, maximo, média)

In [ ]:
#Estatistica
idades.sum()
idades.mean()
idades.max()
idades.describe()

count    19.000000
mean     27.157895
std      12.768290
min      10.000000
25%      14.000000
50%      30.000000
75%      34.500000
max      46.000000
dtype: float64

In [10]:
clientes.head(5)

,idCliente,flEmail,flTwitch,flYouTube,flBlueSky,flInstagram,qtdePontos,DtCriacao,DtAtualizacao
0,000dc0f6-e4f2-4a42-b8cd-b586ed1c709a,0,1,0,0,0,2,2025-11-13 12:03:56.114,2025-12-13 11:45:37.364
1,000ff655-fa9f-4baa-a108-47f581ec52a1,0,0,0,0,0,25086,2024-02-01 00:00:00.000,2025-09-26 13:28:37.697
2,001749bd-37b5-4b1e-8111-f9fbba90f530,0,0,0,0,0,50,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000
3,0019bb9e-26d4-4ebf-8727-fc911ea28a92,0,0,0,0,0,2,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000
4,0028dda2-334f-40bb-9582-475fb6719471,1,1,1,0,0,1100,2025-10-29 02:08:18.367,2026-02-24 04:49:02.551

In [13]:
clientes["flTwitch"].sum()
clientes["flTwitch"].mean()

np.float64(0.7224049707602339)

In [ ]:
redes_sociais = ["flEmail","flTwitch","flYouTube","flBlueSky","flInstagram"]

redes = clientes[redes_sociais]

In [18]:
redes.head(5)

   flEmail  flTwitch  flYouTube  flBlueSky  flInstagram
0        0         1          0          0            0
1        0         0          0          0            0
2        0         0          0          0            0
3        0         0          0          0            0
4        1         1          1          0            0

In [19]:
### se eu aplicar uma agregação na serie ele vai retornar da serie, se vc usar no dataframe ele vai retornar cada um do dataframe
redes.mean()
redes.sum()

flEmail         363
flTwitch       3953
flYouTube       272
flBlueSky         0
flInstagram       0
dtype: int64

In [30]:
### como faz pra pegar só os númericos?
filtro = clientes.dtypes != "str"
redes_sociais_novo = clientes.dtypes[filtro].index.to_list()

In [31]:
clientes[redes_sociais_novo]

      flEmail  flTwitch  flYouTube  flBlueSky  flInstagram  qtdePontos
0           0         1          0          0            0           2
1           0         0          0          0            0       25086
2           0         0          0          0            0          50
3           0         0          0          0            0           2
4           1         1          1          0            0        1100
...       ...       ...        ...        ...          ...         ...
5467        0         1          0          0            0        2021
5468        0         1          0          0            0           0
5469        1         1          1          0            0           0
5470        0         1          0          0            0        1000
5471        0         1          0          0            0           0

[5472 rows x 6 columns]

In [32]:
clientes[redes_sociais_novo].mean()

flEmail          0.066338
flTwitch         0.722405
flYouTube        0.049708
flBlueSky        0.000000
flInstagram      0.000000
qtdePontos     441.755117
dtype: float64

In [33]:
clientes[redes_sociais_novo].describe()

,flEmail,flTwitch,flYouTube,flBlueSky,flInstagram,qtdePontos
count,5472.000000,5472.000000,5472.000000,5472.0,5472.0,5472.000000
mean,0.066338,0.722405,0.049708,0.0,0.0,441.755117
std,0.248894,0.447853,0.217360,0.0,0.0,1330.868496
min,0.000000,0.000000,0.000000,0.0,0.0,-7.000000
25%,0.000000,0.000000,0.000000,0.0,0.0,0.000000
50%,0.000000,1.000000,0.000000,0.0,0.0,51.000000
75%,0.000000,1.000000,0.000000,0.0,0.0,275.250000
max,1.000000,1.000000,1.000000,0.0,0.0,29110.000000

In [ ]:
### Explicação... Se eu fizer a média de uma coluna, ele vai retornar um escalar. Se eu retornar uma média de duas colunas -> vai retornar a serie(com as linhas o nome das colunas e os valores o valor da média).
## o Describe pra uma coluna ele ja retorna uma serie(pq é mais valores)
#se eu passar mais de uma coluna e dar uma describe, ele vai retornar uma dataframe, conjunto de séries.

In [ ]:
## beleza, eu sumarizei, mas e se eu quiser sumarizar por uma coisa especifica? uma quebra. ->>> GROUPBY

In [35]:
transacoes = pd.read_csv("../data/transacoes.csv", sep=";")

In [36]:
transacoes.head(10)

,IdTransacao,IdCliente,DtCriacao,QtdePontos,DescSistemaOrigem
0,0000520a-a4e5-4977-b360-17be62fa0f2b,24782f0b-4683-4f35-976a-ea21d6714ba6,2025-09-17 12:28:41.864,1,twitch
1,000060e8-aa76-4286-a8d7-f30e6fa47edd,252a0923-3f79-45bb-b664-3040235c6c58,2024-07-23 12:49:49.874,1,twitch
2,000095de-3daa-4cfb-a0ae-e7b2c8bc3c9b,30f45a6d-ada5-4a17-8338-710e414eb6c6,2025-09-17 13:38:57.479,1,twitch
3,0000c010-a592-46f7-8b0b-6f841bee64ba,65662aff-44d6-4f06-b9d9-07445c6e5943,2025-10-03 12:23:39.779,1,twitch
4,0000dfbb-e14e-4ea7-a57f-60236869fffe,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,2024-02-20 13:21:45.613,1,twitch
5,0000e94f-fb76-42b7-82e3-5059b6e40703,3884c92f-a635-4b67-9e5a-97730829cdca,2024-02-05 13:27:18.987,1,twitch
6,00017768-81eb-45ae-ad56-f189dd657808,3b878853-34a5-44be-9a8e-05642b853dc6,2025-09-30 12:02:16.448,1,twitch
7,00019b46-6b25-47c3-aa8f-f550d7dbcb00,e2624c1c-c8af-4622-94e0-f3470037292f,2024-06-20 19:22:45.600,1,twitch
8,0001caa0-39a5-4620-baaa-5f6d8db3a412,7df60476-b880-485a-9430-ededf50a9bbb,2026-02-25 12:52:50.780,1,twitch
9,0001d503-58d0-4c3e-b0f4-eda1d5f97d06,9aba2685-7c0a-4d1f-8e22-0c47ca0af580,2024-03-18 13:04:21.814,1,twitch

In [ ]:
### pelo oque vc quer agrupar???

transacoes.groupby(by=["IdCliente"]).count()

## ta aplicando o count pra cada coluna

,IdTransacao,DtCriacao,QtdePontos,DescSistemaOrigem
IdCliente,,,,
000dc0f6-e4f2-4a42-b8cd-b586ed1c709a,2,2,2,2
000ff655-fa9f-4baa-a108-47f581ec52a1,512,512,512,512
001749bd-37b5-4b1e-8111-f9fbba90f530,1,1,1,1
0019bb9e-26d4-4ebf-8727-fc911ea28a92,2,2,2,2
0028dda2-334f-40bb-9582-475fb6719471,4,4,4,4
...,...,...,...,...
ff1ceaef-650c-422b-bdc3-6984e29e7aa5,15,15,15,15
ff2cabd3-3316-4b3f-8494-c25f95e90524,8,8,8,8
ff4909ad-4e52-4767-a6fc-0fbd76e37857,1,1,1,1
ff5d2399-6b53-49f0-b41e-fdaaa0da172a,385,385,385,385
fff7862d-4b2c-4140-a4c5-509b48ed31b4,1,1,1,1

In [ ]:
(transacoes.groupby(by=["IdCliente"])["IdTransacao"].count()).sort_values(ascending=False)

TypeError: DataFrame.sort_values() missing 1 required positional argument: 'by'

In [ ]:
(transacoes.groupby(by=["IdCliente"], as_index=False)[["IdTransacao"]].count()).sort_values(by="IdTransacao",ascending=False)


#entender o reset_index aqui

                                 IdCliente  IdTransacao
1464  65662aff-44d6-4f06-b9d9-07445c6e5943        27185
1389  5f8fcbe0-6014-43f8-8b83-38cf2f4887b3        18461
569   24782f0b-4683-4f35-976a-ea21d6714ba6         8980
2178  961622c3-3c29-4fa1-88d2-4f408d6d6ebb         7079
694   2d3d2dce-d353-4961-ad39-46723efe2100         5925
...                                    ...          ...
45    02d8e64c-cb53-446b-955e-cbbf93c8f747            1
40    02b3d0fe-4404-4401-b1f6-1e4df1af1cab            1
38    028d6ac0-a347-49b3-923f-8cac66926c31            1
36    0272683c-cc20-4fe5-a536-d28449581d89            1
3645  fef56fd8-747a-4793-8fb4-13bc90aade9a            1

[3652 rows x 2 columns]

In [53]:
# Calcular mais de uma estatistica
#qtde_transacoes
# total_pontos
# pontos / transacoes

# agg mesma coisa que aggregate;

summary = (transacoes.groupby(by=["IdCliente"], as_index=False).agg({

    "IdTransacao": ["count"],
    "QtdePontos": ["sum", "mean"]
}

))

In [ ]:
summary.head

                              IdCliente IdTransacao QtdePontos
                                              count        sum        mean
0  000dc0f6-e4f2-4a42-b8cd-b586ed1c709a           2          2    1.000000
1  000ff655-fa9f-4baa-a108-47f581ec52a1         512      25086   48.996094
2  001749bd-37b5-4b1e-8111-f9fbba90f530           1         50   50.000000
3  0019bb9e-26d4-4ebf-8727-fc911ea28a92           2          2    1.000000
4  0028dda2-334f-40bb-9582-475fb6719471           4       1100  275.000000

In [ ]:
### dataframe com multiindex

summary.columns

MultiIndex([(  'IdCliente',      ''),
            ('IdTransacao', 'count'),
            ( 'QtdePontos',   'sum'),
            ( 'QtdePontos',  'mean')],
           )

In [56]:
summary["IdTransacao"]

      count
0         2
1       512
2         1
3         2
4         4
...     ...
3647     15
3648      8
3649      1
3650    385
3651      1

[3652 rows x 1 columns]

In [57]:
summary["QtdePontos"]

        sum         mean
0         2     1.000000
1     25086    48.996094
2        50    50.000000
3         2     1.000000
4      1100   275.000000
...     ...          ...
3647    162    10.800000
3648     57     7.125000
3649     50    50.000000
3650   2021     5.249351
3651   1000  1000.000000

[3652 rows x 2 columns]

In [58]:
summary["QtdePontos"]["mean"]

0          1.000000
1         48.996094
2         50.000000
3          1.000000
4        275.000000
           ...
3647      10.800000
3648       7.125000
3649      50.000000
3650       5.249351
3651    1000.000000
Name: mean, Length: 3652, dtype: float64

In [59]:
summary[("QtdePontos", "mean")]

0          1.000000
1         48.996094
2         50.000000
3          1.000000
4        275.000000
           ...
3647      10.800000
3648       7.125000
3649      50.000000
3650       5.249351
3651    1000.000000
Name: (QtdePontos, mean), Length: 3652, dtype: float64

In [ ]:
#### uma forma melhor de fazer isso;

#forma de ajsutar o multiindex:

summary.columns = ["IdCliente", "qtdeTransacao", "totalpontos", "avg_pontos"] ##### chumba o que é em cada coluna
summary

,IdCliente,qtdeTransacao,totalpontos,avg_pontos
0,000dc0f6-e4f2-4a42-b8cd-b586ed1c709a,2,2,1.000000
1,000ff655-fa9f-4baa-a108-47f581ec52a1,512,25086,48.996094
2,001749bd-37b5-4b1e-8111-f9fbba90f530,1,50,50.000000
3,0019bb9e-26d4-4ebf-8727-fc911ea28a92,2,2,1.000000
4,0028dda2-334f-40bb-9582-475fb6719471,4,1100,275.000000
...,...,...,...,...
3647,ff1ceaef-650c-422b-bdc3-6984e29e7aa5,15,162,10.800000
3648,ff2cabd3-3316-4b3f-8494-c25f95e90524,8,57,7.125000
3649,ff4909ad-4e52-4767-a6fc-0fbd76e37857,1,50,50.000000
3650,ff5d2399-6b53-49f0-b41e-fdaaa0da172a,385,2021,5.249351
3651,fff7862d-4b2c-4140-a4c5-509b48ed31b4,1,1000,1000.000000