In [37]:
import pandas as pd
import numpy as np

In [23]:
df_clientes = pd.read_csv("../data/clientes.csv", sep=";")

In [24]:
df_clientes

,idCliente,flEmail,flTwitch,flYouTube,flBlueSky,flInstagram,qtdePontos,DtCriacao,DtAtualizacao
0,000dc0f6-e4f2-4a42-b8cd-b586ed1c709a,0,1,0,0,0,2,2025-11-13 12:03:56.114,2025-12-13 11:45:37.364
1,000ff655-fa9f-4baa-a108-47f581ec52a1,0,0,0,0,0,25086,2024-02-01 00:00:00.000,2025-09-26 13:28:37.697
2,001749bd-37b5-4b1e-8111-f9fbba90f530,0,0,0,0,0,50,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000
3,0019bb9e-26d4-4ebf-8727-fc911ea28a92,0,0,0,0,0,2,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000
4,0028dda2-334f-40bb-9582-475fb6719471,1,1,1,0,0,1100,2025-10-29 02:08:18.367,2026-02-24 04:49:02.551
...,...,...,...,...,...,...,...,...,...
5467,ff5d2399-6b53-49f0-b41e-fdaaa0da172a,0,1,0,0,0,2021,2025-08-25 13:09:12.556,2026-01-30 14:43:50.139
5468,ff8d55dc-64fa-40de-992a-04a4155f5634,0,1,0,0,0,0,2025-07-12 13:50:37.959,2025-07-12 13:50:37.959
5469,ffcf3b9c-8cc8-4fca-a93a-e01a6fd830f0,1,1,1,0,0,0,2026-05-06 14:42:42.170,2026-05-06 14:44:23.800
5470,fff7862d-4b2c-4140-a4c5-509b48ed31b4,0,1,0,0,0,1000,2025-11-12 01:01:58.698,2025-11-12 01:02:16.561
5471,fff940d1-0786-4ee5-a75a-3bbda4e50f7a,0,1,0,0,0,0,2026-04-29 13:33:15.703,2026-04-29 13:33:15.703

In [25]:
df_clientes["pontos_100"] = df_clientes[["qtdePontos"]] + 100

In [26]:
df_clientes.head(5)

,idCliente,flEmail,flTwitch,flYouTube,flBlueSky,flInstagram,qtdePontos,DtCriacao,DtAtualizacao,pontos_100
0,000dc0f6-e4f2-4a42-b8cd-b586ed1c709a,0,1,0,0,0,2,2025-11-13 12:03:56.114,2025-12-13 11:45:37.364,102
1,000ff655-fa9f-4baa-a108-47f581ec52a1,0,0,0,0,0,25086,2024-02-01 00:00:00.000,2025-09-26 13:28:37.697,25186
2,001749bd-37b5-4b1e-8111-f9fbba90f530,0,0,0,0,0,50,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000,150
3,0019bb9e-26d4-4ebf-8727-fc911ea28a92,0,0,0,0,0,2,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000,102
4,0028dda2-334f-40bb-9582-475fb6719471,1,1,1,0,0,1100,2025-10-29 02:08:18.367,2026-02-24 04:49:02.551,1200

In [27]:
df_clientes["email_twitch"] = df_clientes["flEmail"] + df_clientes["flTwitch"]

In [28]:
df_clientes.head(5)

,idCliente,flEmail,flTwitch,flYouTube,flBlueSky,flInstagram,qtdePontos,DtCriacao,DtAtualizacao,pontos_100,email_twitch
0,000dc0f6-e4f2-4a42-b8cd-b586ed1c709a,0,1,0,0,0,2,2025-11-13 12:03:56.114,2025-12-13 11:45:37.364,102,1
1,000ff655-fa9f-4baa-a108-47f581ec52a1,0,0,0,0,0,25086,2024-02-01 00:00:00.000,2025-09-26 13:28:37.697,25186,0
2,001749bd-37b5-4b1e-8111-f9fbba90f530,0,0,0,0,0,50,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000,150,0
3,0019bb9e-26d4-4ebf-8727-fc911ea28a92,0,0,0,0,0,2,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000,102,0
4,0028dda2-334f-40bb-9582-475fb6719471,1,1,1,0,0,1100,2025-10-29 02:08:18.367,2026-02-24 04:49:02.551,1200,2

In [29]:
df_clientes["flEmail"] * df_clientes["flTwitch"]

0       0
1       0
2       0
3       0
4       1
       ..
5467    0
5468    0
5469    1
5470    0
5471    0
Length: 5472, dtype: int64

In [30]:
df_clientes["qtde_social"] = df_clientes["flEmail"] + df_clientes["flTwitch"] + df_clientes["flYouTube"] + df_clientes["flBlueSky"] + df_clientes["flInstagram"]

In [31]:
df_clientes.head()

,idCliente,flEmail,flTwitch,flYouTube,flBlueSky,flInstagram,qtdePontos,DtCriacao,DtAtualizacao,pontos_100,email_twitch,qtde_social
0,000dc0f6-e4f2-4a42-b8cd-b586ed1c709a,0,1,0,0,0,2,2025-11-13 12:03:56.114,2025-12-13 11:45:37.364,102,1,1
1,000ff655-fa9f-4baa-a108-47f581ec52a1,0,0,0,0,0,25086,2024-02-01 00:00:00.000,2025-09-26 13:28:37.697,25186,0,0
2,001749bd-37b5-4b1e-8111-f9fbba90f530,0,0,0,0,0,50,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000,150,0,0
3,0019bb9e-26d4-4ebf-8727-fc911ea28a92,0,0,0,0,0,2,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000,102,0,0
4,0028dda2-334f-40bb-9582-475fb6719471,1,1,1,0,0,1100,2025-10-29 02:08:18.367,2026-02-24 04:49:02.551,1200,2,3

In [32]:
df_clientes["todas_redes"] = df_clientes["flEmail"] * df_clientes["flTwitch"] * df_clientes["flYouTube"] * df_clientes["flBlueSky"] * df_clientes["flInstagram"]

In [33]:
df_clientes.head(2)

,idCliente,flEmail,flTwitch,flYouTube,flBlueSky,flInstagram,qtdePontos,DtCriacao,DtAtualizacao,pontos_100,email_twitch,qtde_social,todas_redes
0,000dc0f6-e4f2-4a42-b8cd-b586ed1c709a,0,1,0,0,0,2,2025-11-13 12:03:56.114,2025-12-13 11:45:37.364,102,1,1,0
1,000ff655-fa9f-4baa-a108-47f581ec52a1,0,0,0,0,0,25086,2024-02-01 00:00:00.000,2025-09-26 13:28:37.697,25186,0,0,0

In [36]:
df_clientes["qtdePontos"].describe()

count     5472.000000
mean       441.755117
std       1330.868496
min         -7.000000
25%          0.000000
50%         51.000000
75%        275.250000
max      29110.000000
Name: qtdePontos, dtype: float64

In [39]:
np.log(df_clientes["qtdePontos"].describe()+1)

c:\Users\brito\review_pandas\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

count     8.607582
mean      6.093017
std       7.194338
min            NaN
25%       0.000000
50%       3.951244
75%       5.621306
max      10.278871
Name: qtdePontos, dtype: float64