In [12]:
import pandas as pd

In [13]:
df = pd.read_csv("../data/clientes.csv", sep=";")

In [14]:
df.head(2)

,idCliente,flEmail,flTwitch,flYouTube,flBlueSky,flInstagram,qtdePontos,DtCriacao,DtAtualizacao
0,000dc0f6-e4f2-4a42-b8cd-b586ed1c709a,0,1,0,0,0,2,2025-11-13 12:03:56.114,2025-12-13 11:45:37.364
1,000ff655-fa9f-4baa-a108-47f581ec52a1,0,0,0,0,0,25086,2024-02-01 00:00:00.000,2025-09-26 13:28:37.697

In [15]:
df[["qtdePontos"]].sort_values(by="qtdePontos",ascending=False)

      qtdePontos
945        29110
4663       25679
1          25086
534        18613
4810       16777
...          ...
49             0
3592           0
74             0
13             0
225           -7

[5472 rows x 1 columns]

In [16]:
max_pontos = df["qtdePontos"].max()
df[df["qtdePontos"] == max_pontos]

,idCliente,flEmail,flTwitch,flYouTube,flBlueSky,flInstagram,qtdePontos,DtCriacao,DtAtualizacao
945,2a9d4ba3-4c58-47f9-8dc4-6f9cb50be1b1,1,1,0,0,0,29110,2025-03-07 12:59:11.756,2026-04-30 15:08:42.878

In [17]:
top_5_clientes = df.sort_values(by="qtdePontos", ascending=False).head(5)

In [19]:
top_5_clientes[["idCliente"]]

                                 idCliente
945   2a9d4ba3-4c58-47f9-8dc4-6f9cb50be1b1
4663  d7f7eb75-4f0b-4d15-960d-8efe5ca7dd7e
1     000ff655-fa9f-4baa-a108-47f581ec52a1
534   163022e8-12b8-486f-8604-57d8fa0ed7e1
4810  def56b88-a05b-465b-80ee-702831d3f535

In [22]:
(df.sort_values(by="qtdePontos", ascending=False)
 .head(5)[["idCliente"]])

                                 idCliente
945   2a9d4ba3-4c58-47f9-8dc4-6f9cb50be1b1
4663  d7f7eb75-4f0b-4d15-960d-8efe5ca7dd7e
1     000ff655-fa9f-4baa-a108-47f581ec52a1
534   163022e8-12b8-486f-8604-57d8fa0ed7e1
4810  def56b88-a05b-465b-80ee-702831d3f535