In [1]:
import pandas as pd

In [2]:
clientes = pd.read_csv("../data/clientes.csv", sep=";")

In [3]:
clientes.head(5)

,idCliente,flEmail,flTwitch,flYouTube,flBlueSky,flInstagram,qtdePontos,DtCriacao,DtAtualizacao
0,000dc0f6-e4f2-4a42-b8cd-b586ed1c709a,0,1,0,0,0,2,2025-11-13 12:03:56.114,2025-12-13 11:45:37.364
1,000ff655-fa9f-4baa-a108-47f581ec52a1,0,0,0,0,0,25086,2024-02-01 00:00:00.000,2025-09-26 13:28:37.697
2,001749bd-37b5-4b1e-8111-f9fbba90f530,0,0,0,0,0,50,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000
3,0019bb9e-26d4-4ebf-8727-fc911ea28a92,0,0,0,0,0,2,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000
4,0028dda2-334f-40bb-9582-475fb6719471,1,1,1,0,0,1100,2025-10-29 02:08:18.367,2026-02-24 04:49:02.551

In [4]:
clientes.dropna() ###limpa todas as linhas na, se tiver ao menos 1 na

,idCliente,flEmail,flTwitch,flYouTube,flBlueSky,flInstagram,qtdePontos,DtCriacao,DtAtualizacao
0,000dc0f6-e4f2-4a42-b8cd-b586ed1c709a,0,1,0,0,0,2,2025-11-13 12:03:56.114,2025-12-13 11:45:37.364
1,000ff655-fa9f-4baa-a108-47f581ec52a1,0,0,0,0,0,25086,2024-02-01 00:00:00.000,2025-09-26 13:28:37.697
2,001749bd-37b5-4b1e-8111-f9fbba90f530,0,0,0,0,0,50,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000
3,0019bb9e-26d4-4ebf-8727-fc911ea28a92,0,0,0,0,0,2,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000
4,0028dda2-334f-40bb-9582-475fb6719471,1,1,1,0,0,1100,2025-10-29 02:08:18.367,2026-02-24 04:49:02.551
...,...,...,...,...,...,...,...,...,...
5467,ff5d2399-6b53-49f0-b41e-fdaaa0da172a,0,1,0,0,0,2021,2025-08-25 13:09:12.556,2026-01-30 14:43:50.139
5468,ff8d55dc-64fa-40de-992a-04a4155f5634,0,1,0,0,0,0,2025-07-12 13:50:37.959,2025-07-12 13:50:37.959
5469,ffcf3b9c-8cc8-4fca-a93a-e01a6fd830f0,1,1,1,0,0,0,2026-05-06 14:42:42.170,2026-05-06 14:44:23.800
5470,fff7862d-4b2c-4140-a4c5-509b48ed31b4,0,1,0,0,0,1000,2025-11-12 01:01:58.698,2025-11-12 01:02:16.561
5471,fff940d1-0786-4ee5-a75a-3bbda4e50f7a,0,1,0,0,0,0,2026-04-29 13:33:15.703,2026-04-29 13:33:15.703

In [5]:
clientes.dropna(how="all") ###### a linha inteira tem que ser na pra dropa;

,idCliente,flEmail,flTwitch,flYouTube,flBlueSky,flInstagram,qtdePontos,DtCriacao,DtAtualizacao
0,000dc0f6-e4f2-4a42-b8cd-b586ed1c709a,0,1,0,0,0,2,2025-11-13 12:03:56.114,2025-12-13 11:45:37.364
1,000ff655-fa9f-4baa-a108-47f581ec52a1,0,0,0,0,0,25086,2024-02-01 00:00:00.000,2025-09-26 13:28:37.697
2,001749bd-37b5-4b1e-8111-f9fbba90f530,0,0,0,0,0,50,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000
3,0019bb9e-26d4-4ebf-8727-fc911ea28a92,0,0,0,0,0,2,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000
4,0028dda2-334f-40bb-9582-475fb6719471,1,1,1,0,0,1100,2025-10-29 02:08:18.367,2026-02-24 04:49:02.551
...,...,...,...,...,...,...,...,...,...
5467,ff5d2399-6b53-49f0-b41e-fdaaa0da172a,0,1,0,0,0,2021,2025-08-25 13:09:12.556,2026-01-30 14:43:50.139
5468,ff8d55dc-64fa-40de-992a-04a4155f5634,0,1,0,0,0,0,2025-07-12 13:50:37.959,2025-07-12 13:50:37.959
5469,ffcf3b9c-8cc8-4fca-a93a-e01a6fd830f0,1,1,1,0,0,0,2026-05-06 14:42:42.170,2026-05-06 14:44:23.800
5470,fff7862d-4b2c-4140-a4c5-509b48ed31b4,0,1,0,0,0,1000,2025-11-12 01:01:58.698,2025-11-12 01:02:16.561
5471,fff940d1-0786-4ee5-a75a-3bbda4e50f7a,0,1,0,0,0,0,2026-04-29 13:33:15.703,2026-04-29 13:33:15.703

In [6]:
clientes.dropna(how="any") ### (default) se encontrar pelo menos 1 ele tira

,idCliente,flEmail,flTwitch,flYouTube,flBlueSky,flInstagram,qtdePontos,DtCriacao,DtAtualizacao
0,000dc0f6-e4f2-4a42-b8cd-b586ed1c709a,0,1,0,0,0,2,2025-11-13 12:03:56.114,2025-12-13 11:45:37.364
1,000ff655-fa9f-4baa-a108-47f581ec52a1,0,0,0,0,0,25086,2024-02-01 00:00:00.000,2025-09-26 13:28:37.697
2,001749bd-37b5-4b1e-8111-f9fbba90f530,0,0,0,0,0,50,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000
3,0019bb9e-26d4-4ebf-8727-fc911ea28a92,0,0,0,0,0,2,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000
4,0028dda2-334f-40bb-9582-475fb6719471,1,1,1,0,0,1100,2025-10-29 02:08:18.367,2026-02-24 04:49:02.551
...,...,...,...,...,...,...,...,...,...
5467,ff5d2399-6b53-49f0-b41e-fdaaa0da172a,0,1,0,0,0,2021,2025-08-25 13:09:12.556,2026-01-30 14:43:50.139
5468,ff8d55dc-64fa-40de-992a-04a4155f5634,0,1,0,0,0,0,2025-07-12 13:50:37.959,2025-07-12 13:50:37.959
5469,ffcf3b9c-8cc8-4fca-a93a-e01a6fd830f0,1,1,1,0,0,0,2026-05-06 14:42:42.170,2026-05-06 14:44:23.800
5470,fff7862d-4b2c-4140-a4c5-509b48ed31b4,0,1,0,0,0,1000,2025-11-12 01:01:58.698,2025-11-12 01:02:16.561
5471,fff940d1-0786-4ee5-a75a-3bbda4e50f7a,0,1,0,0,0,0,2026-04-29 13:33:15.703,2026-04-29 13:33:15.703

In [7]:
df_brinquedo = pd.DataFrame(
    {
        "nome": ["Téo", None, "Nah", "Marcio"],
        "idade": [None, None, 43, 52],
        "salario": [3453, 4324, None, 5423],
    }
)

In [8]:
df_brinquedo

     nome  idade  salario
0     Téo    NaN   3453.0
1     NaN    NaN   4324.0
2     Nah   43.0      NaN
3  Marcio   52.0   5423.0

In [9]:
df_brinquedo.dropna(how="all")

     nome  idade  salario
0     Téo    NaN   3453.0
1     NaN    NaN   4324.0
2     Nah   43.0      NaN
3  Marcio   52.0   5423.0

In [10]:
df_brinquedo.dropna(how="all", subset=["idade"]) ###dropa o na no dataframe todas as linhas tem que ser Na, mas, o critério ele vai avaliar só a coluna idade;

     nome  idade  salario
2     Nah   43.0      NaN
3  Marcio   52.0   5423.0

In [ ]:
df_brinquedo.dropna(how="any", subset=["idade", "salario"]) #### pelo menos 1 vai te que ser na, qnd uma for na ele tira; Ao menos uma
df_brinquedo.dropna(how="all", subset=["idade", "salario"])  ### as duas precisa ser na pra sumir

     nome  idade  salario
3  Marcio   52.0   5423.0