In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame(
    {
        "nome": ["Téo", None, "Nah", "Marcio", "Téo"],
        "idade": [None, None, 43, 52, 22],
        "salario": [3453, 4324, None, 5423, 2450]
    }
)

In [3]:
df

     nome  idade  salario
0     Téo    NaN   3453.0
1     NaN    NaN   4324.0
2     Nah   43.0      NaN
3  Marcio   52.0   5423.0
4     Téo   22.0   2450.0

In [4]:
df.drop_duplicates()

     nome  idade  salario
0     Téo    NaN   3453.0
1     NaN    NaN   4324.0
2     Nah   43.0      NaN
3  Marcio   52.0   5423.0
4     Téo   22.0   2450.0

In [31]:
import pandas as pd

df = pd.DataFrame({
    "nome": ["teo", "lara", "nah", "bia", "mah", "lara", "mah", "mah", 'mah'],
    "sobrenome": ["calvo", "calvo", "ataide", "ataide", "silva", "silva" , "silva", "silva", 'silva'],
    "salario" :[200,300,2500,4000,6000,12000,120000,6000, 2500]
})

df

   nome sobrenome  salario
0   teo     calvo      200
1  lara     calvo      300
2   nah    ataide     2500
3   bia    ataide     4000
4   mah     silva     6000
5  lara     silva    12000
6   mah     silva   120000
7   mah     silva     6000
8   mah     silva     2500

In [12]:
df

   nome sobrenome  salario
0   teo     calvo      200
1  lara     calvo      300
2   nah    ataide     2500
3   bia    ataide     4000
4   mah     silva     6000
5  lara     silva    12000
6   mah     silva   120000
7   mah     silva     6000

In [13]:
df.drop_duplicates() ### mantem a primeira e remove a última

   nome sobrenome  salario
0   teo     calvo      200
1  lara     calvo      300
2   nah    ataide     2500
3   bia    ataide     4000
4   mah     silva     6000
5  lara     silva    12000
6   mah     silva   120000

In [7]:
df

   nome sobrenome  salario
0   teo     calvo      200
1  lara     calvo      300
2   nah    ataide     2500
3   bia    ataide     4000
4   mah     silva     6000
5  lara     silva    12000
6   mah     silva   120000
7   mah     silva     6000

In [14]:
df.drop_duplicates(subset=["nome", "sobrenome"]) ####mantem a ultima

   nome sobrenome  salario
0   teo     calvo      200
1  lara     calvo      300
2   nah    ataide     2500
3   bia    ataide     4000
4   mah     silva     6000
5  lara     silva    12000

In [15]:
df = df.sort_values("salario", ascending=False)
df = df.drop_duplicates(keep='last', subset=["nome","sobrenome"])

In [28]:
df_novo = df.sort_values("salario", ascending=False)

In [29]:
df_novo

   nome sobrenome  salario
6   mah     silva   120000
5  lara     silva    12000
4   mah     silva     6000
7   mah     silva     6000
3   bia    ataide     4000
8   mah     silva     2500
2   nah    ataide     2500
1  lara     calvo      300
0   teo     calvo      200

In [30]:
df_novo.drop_duplicates(keep='first', subset=["sobrenome","nome"])

   nome sobrenome  salario
6   mah     silva   120000
5  lara     silva    12000
3   bia    ataide     4000
2   nah    ataide     2500
1  lara     calvo      300
0   teo     calvo      200

In [33]:
df_novo = (df.sort_values("salario", ascending=False)
           .drop_duplicates(keep="last", subset=["sobrenome", "nome"]))

df_novo

   nome sobrenome  salario
5  lara     silva    12000
3   bia    ataide     4000
8   mah     silva     2500
2   nah    ataide     2500
1  lara     calvo      300
0   teo     calvo      200