In [16]:
import pandas as pd

In [17]:
#Selecione a primeira transação diaria

df_transacao = pd.read_csv("../data/transacoes.csv", sep=";")

In [18]:
df_transacao.head(5)

,IdTransacao,IdCliente,DtCriacao,QtdePontos,DescSistemaOrigem
0,0000520a-a4e5-4977-b360-17be62fa0f2b,24782f0b-4683-4f35-976a-ea21d6714ba6,2025-09-17 12:28:41.864,1,twitch
1,000060e8-aa76-4286-a8d7-f30e6fa47edd,252a0923-3f79-45bb-b664-3040235c6c58,2024-07-23 12:49:49.874,1,twitch
2,000095de-3daa-4cfb-a0ae-e7b2c8bc3c9b,30f45a6d-ada5-4a17-8338-710e414eb6c6,2025-09-17 13:38:57.479,1,twitch
3,0000c010-a592-46f7-8b0b-6f841bee64ba,65662aff-44d6-4f06-b9d9-07445c6e5943,2025-10-03 12:23:39.779,1,twitch
4,0000dfbb-e14e-4ea7-a57f-60236869fffe,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,2024-02-20 13:21:45.613,1,twitch

In [8]:
transacoes = df_transacao.sort_values("DtCriacao", ascending=False)

In [9]:
transacoes["data"] = pd.to_datetime(transacoes["DtCriacao"]).dt.date

In [10]:
transacoes

,IdTransacao,IdCliente,DtCriacao,QtdePontos,DescSistemaOrigem,data
90393,47ec9f3b-14e5-4687-bbe7-dc9ad6bfd4fa,820c0e06-c405-4979-8975-ecfa17abb0f9,2026-05-23 14:56:57.557,50,twitch,2026-05-23
271759,d7bf0fe7-8bff-4b35-87c8-ac3bfcf07ccb,820c0e06-c405-4979-8975-ecfa17abb0f9,2026-05-23 14:56:39.320,50,twitch,2026-05-23
32307,19880618-a3e6-4400-a379-207a885ce06f,ad4915a3-9308-4136-83e8-af675131ecd4,2026-05-23 14:24:52.997,-10,cursos,2026-05-23
308877,f53158f2-88a4-40d5-b4ea-8b7af32b170d,163022e8-12b8-486f-8604-57d8fa0ed7e1,2026-05-23 14:18:11.421,50,twitch,2026-05-23
106766,54f91366-56fa-49b1-a8a5-00a9fdf0b439,163022e8-12b8-486f-8604-57d8fa0ed7e1,2026-05-23 14:17:55.430,50,twitch,2026-05-23
...,...,...,...,...,...,...
292554,e84703a6-b606-4096-a2f3-514971c16c5c,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,2024-01-27 12:31:46.288,500,twitch,2024-01-27
4613,03974c58-e86e-4b6b-8143-8f89ca870d09,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,2024-01-27 12:19:41.063,1,twitch,2024-01-27
20344,10166182-a164-4608-8cdf-35e4450b2bd7,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,2024-01-27 12:11:44.728,500,twitch,2024-01-27
4398,036b8d66-8adf-479b-ba0f-cb0e3207acb0,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,2024-01-27 11:53:24.643,1,twitch,2024-01-27
316592,fb4e3102-6125-414e-b086-e7f641e38f93,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,2024-01-27 11:53:23.774,1,twitch,2024-01-27

In [13]:
transacoes_first_transaction = transacoes.drop_duplicates(keep='first', subset=["IdCliente", 'data'])

In [14]:
transacoes_first_transaction.head(5)

,IdTransacao,IdCliente,DtCriacao,QtdePontos,DescSistemaOrigem,data
90393,47ec9f3b-14e5-4687-bbe7-dc9ad6bfd4fa,820c0e06-c405-4979-8975-ecfa17abb0f9,2026-05-23 14:56:57.557,50,twitch,2026-05-23
32307,19880618-a3e6-4400-a379-207a885ce06f,ad4915a3-9308-4136-83e8-af675131ecd4,2026-05-23 14:24:52.997,-10,cursos,2026-05-23
308877,f53158f2-88a4-40d5-b4ea-8b7af32b170d,163022e8-12b8-486f-8604-57d8fa0ed7e1,2026-05-23 14:18:11.421,50,twitch,2026-05-23
474,005cfd74-deb6-4176-9570-ea3fc30c6954,054366e2-a4bb-44ec-8abe-dbcecc3fbdbe,2026-05-23 14:11:50.826,1000,cursos,2026-05-23
319780,fdcf8e58-1dc2-46ef-8909-0801e5a68ca1,02bfd4d9-4dd6-44e5-88b8-2cc08caf3267,2026-05-22 23:48:31.571,-7300,cursos,2026-05-22

In [15]:
filtro = transacoes_first_transaction["IdCliente"] == "820c0e06-c405-4979-8975-ecfa17abb0f9"
transacoes_first_transaction[filtro]

,IdTransacao,IdCliente,DtCriacao,QtdePontos,DescSistemaOrigem,data
90393,47ec9f3b-14e5-4687-bbe7-dc9ad6bfd4fa,820c0e06-c405-4979-8975-ecfa17abb0f9,2026-05-23 14:56:57.557,50,twitch,2026-05-23
196573,9c2bccc2-0ca7-4a81-88b2-6ba684111c40,820c0e06-c405-4979-8975-ecfa17abb0f9,2026-05-22 15:15:42.266,1,twitch,2026-05-22
264837,d242680e-c0e9-4ad0-8c43-bfd4c7efe168,820c0e06-c405-4979-8975-ecfa17abb0f9,2026-05-21 14:12:44.211,1,twitch,2026-05-21
104599,5339b205-3335-4306-b90d-41ea0c784d58,820c0e06-c405-4979-8975-ecfa17abb0f9,2026-05-20 13:58:29.259,1,twitch,2026-05-20
259208,cdc3e6af-4ad0-43e0-ab4e-0fce49d3adaa,820c0e06-c405-4979-8975-ecfa17abb0f9,2026-05-19 19:49:05.865,-1000,twitch,2026-05-19
...,...,...,...,...,...,...
285059,e257230a-b4c9-4399-b714-f7fde1ec9281,820c0e06-c405-4979-8975-ecfa17abb0f9,2024-03-02 00:57:03.091,1,twitch,2024-03-02
193187,9996ef54-7ddf-4588-a357-88ce479141d4,820c0e06-c405-4979-8975-ecfa17abb0f9,2024-03-01 11:59:02.505,50,twitch,2024-03-01
239874,be6ab093-aa63-47ed-b828-981851419ddb,820c0e06-c405-4979-8975-ecfa17abb0f9,2024-02-29 23:00:40.015,50,twitch,2024-02-29
83532,426cf8ca-6d76-4a3f-87ba-ee3250621ca1,820c0e06-c405-4979-8975-ecfa17abb0f9,2024-02-28 12:28:29.737,50,twitch,2024-02-28
116345,5c9dd96c-bd6f-41a2-aae1-b394b8372fa4,820c0e06-c405-4979-8975-ecfa17abb0f9,2024-02-27 22:55:22.013,50,twitch,2024-02-27

In [19]:
df_transacao.head(5)

,IdTransacao,IdCliente,DtCriacao,QtdePontos,DescSistemaOrigem
0,0000520a-a4e5-4977-b360-17be62fa0f2b,24782f0b-4683-4f35-976a-ea21d6714ba6,2025-09-17 12:28:41.864,1,twitch
1,000060e8-aa76-4286-a8d7-f30e6fa47edd,252a0923-3f79-45bb-b664-3040235c6c58,2024-07-23 12:49:49.874,1,twitch
2,000095de-3daa-4cfb-a0ae-e7b2c8bc3c9b,30f45a6d-ada5-4a17-8338-710e414eb6c6,2025-09-17 13:38:57.479,1,twitch
3,0000c010-a592-46f7-8b0b-6f841bee64ba,65662aff-44d6-4f06-b9d9-07445c6e5943,2025-10-03 12:23:39.779,1,twitch
4,0000dfbb-e14e-4ea7-a57f-60236869fffe,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,2024-02-20 13:21:45.613,1,twitch

In [20]:
df_transacao["data"] = pd.to_datetime(df_transacao["DtCriacao"])

In [21]:
df_transacao.head(5)

,IdTransacao,IdCliente,DtCriacao,QtdePontos,DescSistemaOrigem,data
0,0000520a-a4e5-4977-b360-17be62fa0f2b,24782f0b-4683-4f35-976a-ea21d6714ba6,2025-09-17 12:28:41.864,1,twitch,2025-09-17 12:28:41.864
1,000060e8-aa76-4286-a8d7-f30e6fa47edd,252a0923-3f79-45bb-b664-3040235c6c58,2024-07-23 12:49:49.874,1,twitch,2024-07-23 12:49:49.874
2,000095de-3daa-4cfb-a0ae-e7b2c8bc3c9b,30f45a6d-ada5-4a17-8338-710e414eb6c6,2025-09-17 13:38:57.479,1,twitch,2025-09-17 13:38:57.479
3,0000c010-a592-46f7-8b0b-6f841bee64ba,65662aff-44d6-4f06-b9d9-07445c6e5943,2025-10-03 12:23:39.779,1,twitch,2025-10-03 12:23:39.779
4,0000dfbb-e14e-4ea7-a57f-60236869fffe,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,2024-02-20 13:21:45.613,1,twitch,2024-02-20 13:21:45.613

In [26]:
first = (df_transacao.sort_values("DtCriacao")
         .drop_duplicates(keep="first", subset=["IdCliente", "data"]))

first["fonte"] = "first"

In [27]:
last = (df_transacao.sort_values("DtCriacao")
         .drop_duplicates(keep="last", subset=["IdCliente", "data"]))

last["fonte"] = "last"

In [28]:
last.head(5)

,IdTransacao,IdCliente,DtCriacao,QtdePontos,DescSistemaOrigem,data,fonte
316592,fb4e3102-6125-414e-b086-e7f641e38f93,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,2024-01-27 11:53:23.774,1,twitch,2024-01-27 11:53:23.774,last
4398,036b8d66-8adf-479b-ba0f-cb0e3207acb0,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,2024-01-27 11:53:24.643,1,twitch,2024-01-27 11:53:24.643,last
20344,10166182-a164-4608-8cdf-35e4450b2bd7,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,2024-01-27 12:11:44.728,500,twitch,2024-01-27 12:11:44.728,last
4613,03974c58-e86e-4b6b-8143-8f89ca870d09,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,2024-01-27 12:19:41.063,1,twitch,2024-01-27 12:19:41.063,last
292554,e84703a6-b606-4096-a2f3-514971c16c5c,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,2024-01-27 12:31:46.288,500,twitch,2024-01-27 12:31:46.288,last

In [30]:
df_concatenado  = pd.concat([first,last])

In [35]:
df_concatenado.sample(15)

,IdTransacao,IdCliente,DtCriacao,QtdePontos,DescSistemaOrigem,data,fonte
151258,783371bd-fc42-40c0-9717-edffab6a17bb,752d53df-332a-4bcc-a673-3258583aa133,2025-06-17 12:04:09.772,50,twitch,2025-06-17 12:04:09.772,last
161443,80541f5a-4b3e-41e4-bddd-43ab1e173dce,8cb9a750-e03b-4eb9-aafd-ea9314e756df,2026-04-16 11:55:55.235,1,twitch,2026-04-16 11:55:55.235,first
252331,c84a2342-41d2-402b-b9ab-e47748ca5bea,3bc4f69e-1b1e-468d-aa10-69759a956ede,2025-02-21 12:19:56.214,1,twitch,2025-02-21 12:19:56.214,first
33110,1a292b0f-3a37-46b0-a34a-ac9b406f82e9,562a52df-380d-4b01-877a-691969236f13,2025-02-06 11:50:52.428,1,twitch,2025-02-06 11:50:52.428,last
276697,db9ea703-d46d-4f12-94b0-1f0efff84380,000ff655-fa9f-4baa-a108-47f581ec52a1,2024-04-10 14:14:58.841,1,twitch,2024-04-10 14:14:58.841,last
304581,f1c0658a-0954-4ef4-9d7b-4b781b92e024,0f1215d3-caf2-4533-8ed0-ce2eb106c589,2025-06-26 12:33:21.481,1,twitch,2025-06-26 12:33:21.481,first
144309,72bcc887-b10e-45a4-b4b1-d21ed3f3929a,58a4cb1c-e1f1-4906-a86d-59736a95f50e,2025-02-19 12:05:06.779,1,twitch,2025-02-19 12:05:06.779,last
216427,abb9e027-a7d3-4f75-a028-ee618738403e,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,2024-03-14 01:46:58.399,1,twitch,2024-03-14 01:46:58.399,first
80587,401168da-3ef2-49d1-bbc7-89fef2f1e8a8,08a0c6c0-1f86-4c58-bc7e-ffc866f07eb7,2025-03-24 12:43:14.645,1,twitch,2025-03-24 12:43:14.645,last
213826,a9b9ddcd-3c5b-467f-aa71-0e187566f9e5,056caf66-d67b-449e-8cba-0bab8aca5949,2026-04-16 12:21:15.214,50,twitch,2026-04-16 12:21:15.214,last
143610,723069a7-4fe1-4c59-bf2a-7da2cd33a9b0,65662aff-44d6-4f06-b9d9-07445c6e5943,2025-08-06 13:24:43.686,1,twitch,2025-08-06 13:24:43.686,last
32034,194ef2bb-20ef-424d-b716-213fbe57208d,1856963a-84cb-453e-a139-eb7d8d9b3255,2025-10-22 12:06:29.177,1,twitch,2025-10-22 12:06:29.177,last
173999,8a6278a5-807f-42cb-b01d-b8cb7bfc72f9,961622c3-3c29-4fa1-88d2-4f408d6d6ebb,2025-06-19 12:09:12.315,1,twitch,2025-06-19 12:09:12.315,first
300393,ee7548d3-468a-4e2e-919a-7b053b2194fa,961622c3-3c29-4fa1-88d2-4f408d6d6ebb,2024-07-01 14:10:29.100,1,twitch,2024-07-01 14:10:29.100,last
224214,b1ef8475-f56a-428a-9136-daed3a9f5f6d,b0847d5b-c1dd-41cc-8302-b451c8674c0e,2024-03-19 13:01:33.852,1,twitch,2024-03-19 13:01:33.852,last