In [8]:
import pandas as pd

In [9]:
df_brinquedo = pd.DataFrame(
    {
        "nome": ["Téo", None, "Nah", "Marcio"],
        "idade": [None, None, 43, 52],
        "salario": [3453, 4324, None, 5423],
    }
)

In [3]:
df_brinquedo

     nome  idade  salario
0     Téo    NaN   3453.0
1     NaN    NaN   4324.0
2     Nah   43.0      NaN
3  Marcio   52.0   5423.0

In [ ]:
df_brinquedo.fillna(0) #### imputa um valor do NA

     nome  idade  salario
0     Téo    0.0   3453.0
1       0    0.0   4324.0
2     Nah   43.0      0.0
3  Marcio   52.0   5423.0

In [5]:
df_brinquedo

     nome  idade  salario
0     Téo    NaN   3453.0
1     NaN    NaN   4324.0
2     Nah   43.0      NaN
3  Marcio   52.0   5423.0

In [6]:
df_brinquedo.fillna({
    "nome": "alguem",
    "idade": 0
})

     nome  idade  salario
0     Téo    0.0   3453.0
1  alguem    0.0   4324.0
2     Nah   43.0      NaN
3  Marcio   52.0   5423.0

In [13]:
df_brinquedo.fillna(df_brinquedo[["idade","salario"]].mean())

     nome  idade  salario
0     Téo   47.5   3453.0
1     NaN   47.5   4324.0
2     Nah   43.0   4400.0
3  Marcio   52.0   5423.0

In [ ]:
medias = df_brinquedo[["idade","salario"]].mean()


df_brinquedo.fillna(medias)